package cvut.cz.Map;

import java.util.ArrayList;
import java.util.List;
import java.net.URL;

/**
 * Handles slicing a source image of a map into individual tiles based on the provided parameters.
 */
public class MapSlicer {
    // The list of sliced tiles
    private List<Tile> slicedTiles;
    // The URL to the source image of the map
    private final URL pathToTiles;

    // The gap between tiles in the X direction in the source image
    private final int gapBetweenTilesX;
    // The gap between tiles in the Y direction in the source image
    private final int gapBetweenTilesY;

    // The number of tiles in a row in the source image
    private final int numberOfTilesInRow;
    // The total number of tiles to be sliced from the source image
    private final int numberOfTiles;

    // The size of each tile in the source image
    private final int sourceTileSize;

    /**
     * Constructs a MapSlicer object with the specified parameters.
     *
     * @param pathToTiles The path to the source image containing the tiles.
     * @param sourceTileSize The size of each tile in the source image.
     * @param gapBetweenTilesX The horizontal gap between tiles in the source image.
     * @param gapBetweenTilesY The vertical gap between tiles in the source image.
     * @param numberOfTilesInRow The number of tiles in a single row of the source image.
     * @param numberOfTiles The total number of tiles in the source image.
     */
    public MapSlicer(URL pathToTiles, int sourceTileSize, int gapBetweenTilesX, int gapBetweenTilesY, int numberOfTilesInRow, int numberOfTiles) {
        this.sourceTileSize = sourceTileSize;
        this.pathToTiles = pathToTiles;
        this.gapBetweenTilesX = gapBetweenTilesX;
        this.gapBetweenTilesY = gapBetweenTilesY;
        this.numberOfTilesInRow = numberOfTilesInRow;
        this.numberOfTiles = numberOfTiles;
    }

    /**
     * Slices the map into individual tiles and stores them in the slicedTiles list.
     */
    public void sliceMap() {
        slicedTiles = new ArrayList<>();
        int rowCounter = 0;
        int columnCounter = 0;

        for (int i = 0; i < numberOfTiles; i++) {
            if (columnCounter == numberOfTilesInRow) {
                columnCounter = 0;
                rowCounter++;
            }
            slicedTiles.add(new Tile(pathToTiles, columnCounter * (sourceTileSize + gapBetweenTilesX), rowCounter * (sourceTileSize + gapBetweenTilesY)));
            columnCounter++;
        }
    }

    /**
     * Gets the list of tiles generated by slicing the map.
     *
     * @return The list of sliced tiles.
     */
    public List<Tile> getSlicedTiles() { return slicedTiles; }
}